### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by OpaVote** [tianhuil/gae_pylint_plugin#1]
Hi tian,

Thanks for making this plugin available.  I just tried it and got an error.  Pasted the traceback below.  Would appreciate it if you know a fix.

Jeff

$ pylint --load-plugins gae_pylint_plugin models.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylint/**init**.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylint/lint.py", line 1242, in **init**
    linter.load_plugin_modules(self._plugins)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylint/lint.py", line 498, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroid/modutils.py", line 137, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astroid/modutils.py", line 180, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gae_pylint_plugin.py", line 4, in <module>
    from google.appengine.ext import ndb
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/__init__.py", line 7, in <module>
    from tasklets import *
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 69, in <module>
    from .google_imports import apiproxy_stub_map
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/google_imports.py", line 15, in <module>
    from google.appengine.api.blobstore import blobstore as api_blobstore
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/api/blobstore/**init**.py", line 23, in <module>
    from blobstore import *
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/api/blobstore/blobstore.py", line 39, in <module>
    from google.appengine.api import datastore
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/api/datastore.py", line 63, in <module>
    from google.appengine.datastore import datastore_query
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_query.py", line 66, in <module>
    from google.appengine.datastore import datastore_index
  File "/Users/joneill/google-cloud-sdk/platform/google_appengine/google/appengine/datastore/datastore_index.py", line 61, in <module>
    import yaml
ImportError: No module named yaml

**Comment by tianhuil** [comment]
This looks like a GAE bug.  I would suggest you ensure that you have the library installed via pip.
